#!/usr/bin/env bash
# Install nginx web server and add ellow world to index page

sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start
echo "Hello World!" | sudo tee /var/www/html/index.html
