#!/usr/bin/env bash
# Install your load balancer

apt-get update
apt-get -y install haproxy

sed -i -e '$ afrontend http_front \n\tbind *:80 \
\tmode http \
\tdefault_backend http_rear \
\nbackend http_rear \
\tbalance		roundrobin \

service haproxy restart
