#!/usr/bin/env bash
# Install your load balancer

apt-get update
apt-get -y install haproxy

sed -i -e '$ afrontend http_front \n\tbind *:80 \
\tmode http \
\tdefault_backend http_rear \
\nbackend http_rear \
\tbalance		roundrobin \
\tserver 252051-web-01		35.175.64.173:80 check \
\tserver 252051-web-02		54.158.205.17:80 check' /etc/haproxy/haproxy.cfg

service haproxy restart
