#!/usr/bin/env bash
# This script controls iteration at 4 and 8 else best school 
index=1
while ((index <= 10))
do  
    if ((index == 4))
    then
        echo "bad luck"
    elif ((index == 8))
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((index++))
done
