#!/usr/bin/env bash
#usin while and case for program flow
i=1
while ((i <= 20))
	do
	echo "$i"
	case $i in
	4) echo "bad luck from China"
		;;
	8) echo "bad luck from Japan"
		;;
	17) echo "bad luck from Italy"
		;;
	esac
	((i++))
done
