#!/usr/bin/env bash
# configure home from 127.0.0.1 to 127.0.0.2
cp /etc/hosts ~/hosts.new 
echo '8.8.8.8   facebook.com' >> ~/hosts.new 
sed -i 's/127.0.0.1/127.0.0.2/' ~/hosts.new 
cp -f ~/hosts.new /etc/hosts 
rm ~/hosts.new
